name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # 或 '18'

    - name: Clean npm cache
      run: npm cache clean --force

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build && npm run export

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out

    - name: Display package.json content
      run: cat package.json

    - name: Check Node.js and npm versions
      run: |
        node --version
        npm --version

    - name: Install Next.js
      run: npm install next@latest

    - name: Install other dependencies
      run: npm install
